manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: my-repo
      url-base: https://github.com/my-github
    ##- name: badjeff    # <-- PMW3610
    ##  url-base: https://github.com/badjeff
    ##- name: caksoylar  # <-- RGB LED
    ##  url-base: https://github.com/caksoylar  
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.2.1
      import: app/west.yml
    #- name: zmk-pmw3610-driver
    #  remote: badjeff
    #  revision: v0.2.1
    #- name: zmk-rgbled-widget
    #  remote: caksoylar
    #  revision: main
  self:
    path: config
